version: '3.8'

services:
  # Main Theia-OpenCog application for local development
  theia-opencog-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AI_OPENCOG_ENVIRONMENT=development
      - AI_OPENCOG_LOG_LEVEL=debug
      - AI_OPENCOG_METRICS_ENABLED=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - opencog-dev-network

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - opencog-dev-network

volumes:
  redis-dev-data:

networks:
  opencog-dev-network:
    driver: bridge
    name: theia-opencog-dev